

org: adghayes
app: noisepuff
service: ffmpeg

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  region: ca-central-1

package:
  exclude: 
    - .serverless-offline/**
    - test/**
    - .npmignore

functions:
  transcode:
    runtime: nodejs12.x
    handler: index.handler
    layers:
      - arn:aws:lambda:ca-central-1:086163355854:layer:ffmpeg-git-20201128-amd64-static:2
    environment:
      BINARY_DIR: /opt/ffmpeg-git-20201128-amd64-static/
      FFMPEG_LOG: 1


plugins:
  - serverless-offline

custom:
  serverless-offline:
    useDocker: true