AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ffmpeg-microservice

  serverless audio transcoding service

Resources:
  Ffmpeg:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs12.x
      FunctionName: ffmpeg-microservice
      MemorySize: 1024
      Timeout: 30
      Environment:
        Variables:
          BINARY_DIR: /usr/local/bin/ffmpeg
      Layers:
        - arn:aws:lambda:ca-central-1:086163355854:layer:ffmpeg-git-20201128-amd64-static:1
  Bucket:
    Type: AWS::S3::Bucket

